

all: 3-1 3-2 3-3 3-4

3-1:
	./hw3_p1.sh ./test_output/fig1-4.png

3-2:
	./hw3_p2.sh ./test_output/fig2-2.png

3-3:
	./hw3_p3.sh ./hw3_data/digits/mnistm/test mnistm ./test_output/mnistm.csv
	./hw3_p3.sh ./hw3_data/digits/svhn/test svhn ./test_output/svhn.csv
	./hw3_p3.sh ./hw3_data/digits/usps/test usps ./test_output/usps.csv

3-4:
	./hw3_p4.sh ./hw3_data/digits/mnistm/test mnistm ./test_output/mnistm.csv
	./hw3_p4.sh ./hw3_data/digits/svhn/test svhn ./test_output/svhn.csv
	./hw3_p4.sh ./hw3_data/digits/usps/test usps ./test_output/usps.csv



